### ISSUE TITLE
window.onResize is a memory leak and does not allow multiple dwv app instances at once

### ISSUE THREAD

**Issue by KillerCodeMonkey** [ivmartel/dwv#705] opened 2020-02-17 17:24 UTC
Hey @bassosimone ,

i am using multiple instances of dwv on one page within an angular project.
I have a list of dicom images i render on a page.
If you click on one dicom i open a detail modal/dialog with additional functionalities.
After closing the modal, the element with the containerDivId does not exists anymore but the global `windows.onresize` listener is triggered with the last added dwv app.

**Problem 1**:
- you should not add a global listener that is overwritten for each app. Just use `window.addEventListener` to allow to resize multiple elements.

**Problem 2**
- this single listener is a memoryleak because the last added app is not removed from the heap as long as there is the onresize listener :)

**Problem 3**
- without using addEventListener other usage of  `window.onresize` in a project gets overwritten. Or your resize listener gets overwritten (maybe)

So it would be nice if you would use add- and removeEventListener, to create and cleanup the events

**Comment by KillerCodeMonkey** [comment] 2020-02-18 12:58
@ivmartel if i have time i could send a PR, but i do not know, how to know when to remove the resize listener.

using `window.addEventListener` is an easy solution to not overwrite other `onresize` handlers, but how do we know, when the "app" should be destroyed?

**Comment by ivmartel** [comment] 2020-02-18 14:45
Thanks for pointing this out! I will move this out of dwv, leaving it to the client to decide if they want to bind or not to the resize event.

And thanks a lot for your donation!

**Comment by KillerCodeMonkey** [comment] 2020-02-18 14:47
no probs :). I am an open source software developer.

Could you please check if your resizing only works, when the window gets smaller?
if i make the window smaller it is working, but if i expand the window again the canvas is not growing as expected

**Comment by ivmartel** [comment] 2020-02-19 14:44
Resizing is working properly for dwv-jqmobile. Not sure about dwv-jqui... Which one are you using?

**Comment by KillerCodeMonkey** [comment] 2020-02-19 14:52
plain dwv ... no jquery i am using it in an ionic (angular) app

**Comment by ivmartel** [comment] 2020-02-19 17:15
Does it complain about the `getElement` method? In theory, you should provide an implementation for it, something like `dwv.gui.getElement = dwv.gui.base.getElement;`. I need to get rid of this...

**Comment by KillerCodeMonkey** [comment] 2020-02-19 17:22
nope, because it is working when the container of the canvas gets smaller. but it does not expand when the container gets bigger.

So i did everything what is needed ;-).

**Comment by ivmartel** [comment] 2020-03-04 10:56
Sorry, I can't reproduce your problem... I tried dwv-jqmobile and dwv-angular (branch [120-dwv-0-27](https://github.com/ivmartel/dwv-angular/tree/120-dwv-0-27)) in Firefox (v73) and Chrome (v80) by changing the size of the browser window and the view adapts properly, getting bigger or smaller.

**Comment by ivmartel** [comment] 2020-03-06 10:58
Closing this issue since the leak is fixed. Please create another one if your resizing problem persists.

**Closed by ivmartel** 2020-03-06 10:58 UTC
Labels: bug

**Comment by KillerCodeMonkey** [comment] 2020-03-06 11:06
Nice Thing. Thanks for The fix :).

ivmartel <notifications@github.com> schrieb am Fr., 6. März 2020, 11:58:
