### ISSUE TITLE
canvas sizing problem

### ISSUE THREAD

**Issue by pawelarybak** [ivmartel/dwv#573] opened 2018-09-19 08:53 UTC
Hi, I am creating app, where you can preview DICOM files and I encountered a problem.
When I have some dcm opened it sets .layerContainer size to arbitrary value.
When changing to another image (by using loadURLs once again) it sets new size of .layerContainer with respect to previous value and not parent's size. This can lead to decreasing image size.

Let me provide an example:
I load an image that sets container to:
```<div class="layerContainer" style="width:650px;height:650px">```
Next I load another picture, which isn't square, container is:
```<div class="layerContainer" style="width:650px;height:417px">```
Then I go back to the first image and container's tag is:
```<div class="layerContainer" style="width:417px;height:417px">```

And because of this container size, canvas size is also decreasing.

Commenting out [this line](https://github.com/ivmartel/dwv/blob/c0f2f056a86dbe0efaea19390b0c852602cb6361/src/app/application.js#L685) helps in my case but I guess there is a reason for that line in there. I'm not sure if it won't break something else.

UPDATE: I created a [fiddle](https://jsfiddle.net/8xmruou2/36/). Open this and try changing from one picture to another and back and watch it getting smaller.

**Comment by tillmon** [comment] 2019-03-11 15:58
On iOS Safari I get the following error opening large files:

> Canvas area exceeds the maximum limit (width * height > 16777216)

**Comment by ivmartel** [comment] 2019-05-06 12:29
Sorry for taking so long to answer, even though time seems to have helped, the issue you encountered is not present any more  with at least version 0.25. Your fiddle uses v0.22. In between I changed the way the canvas size is calculated, check out #579.

Closing for now, feel free to comment if you need.

**Closed by ivmartel** 2019-05-06 12:29 UTC
Labels: question

**Comment by pawelarybak** [comment] 2020-03-30 08:44
Everything working as it should. Thanks.

**Comment by MounikaAV** [comment] 2020-08-12 05:11
Hi, 
I am trying to implement dwv-angular, and I am facing this canvas sizing problem. Can you help me how to do this ?

**Comment by ivmartel** [comment] 2020-08-31 15:33
Hi @MounikaAV, could you give more feedback please? Is the issue caused by dwv or is it specific to dwv-angular (if it is, could you create another issue on [dwv-angular](https://github.com/ivmartel/dwv-angular)) ?
